changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - '**/*.test.{js,ts}'
  - packages/*/tests/**
  - .yarn/cache/**

cloneConcurrency: 8

defaultSemverRangePrefix: ^

enableGlobalCache: false

enableMirror: true

nmMode: hardlinks-local

nodeLinker: node-modules
npmRegistryServer: 'https://npm.pkg.github.com'
npmScopes:
  bitflight-devops:
    npmAlwaysAuth: true
    npmAuditRegistry: 'https://npm.pkg.github.com'
    # npmAuthToken: '${GITHUB_NPM_TOKEN:-}'
    npmPublishRegistry: 'https://npm.pkg.github.com'
    npmRegistryServer: 'https://npm.pkg.github.com'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: '@yarnpkg/plugin-constraints'
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: '@yarnpkg/plugin-stage'

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-3.2.1.cjs
