name: 📓 GitHub Action's Readme Generator
author: Jamie Nelson <jamie@bitflight.io>
description: >
  This is a CLI tool and GitHub Action that reads in the details from a
  GitHub Action's `action.yml` file and updates the `README.md` file
  with the `name`, `description`, `usage`, `inputs`, `outputs`, and
  examples of the action.
  Configuration can be provided via a `.ghadocs.json` file stored in the
  root directory of the Action's repository, via the command line when
  using the cli, or via the `with:` section of this Action.

  This tool uses markdown comments as delimiting tokens within the `README.md`
  file to determine where to place the generated content.

  [`README.example.md`](README.example.md) example with all fields filled in, and no other free-form content.

inputs:
  action:
    description: >
      The absolute or relative path to the `action.yml` file to read in from.
    required: false
    default: action.yml
  readme:
    description: >
      The absolute or relative path to the markdown output file that contains
      the formatting tokens within it.
    required: false
    default: README.md
  owner:
    description: >
      The GitHub Action repository owner. i.e: `bitflight-devops`
    required: true
  repo:
    description: >
      The GitHub Action repository name. i.e: `github-action-readme-generator`
  save:
    description: >
      Save the provided values in a `.ghadocs.json` file. This will update
      any existing `.ghdocs.json` file that is in place.
    required: false
    default: false
