name: 📓 GitHub Action's Readme Generator
author: Jamie Nelson <jamie@bitflight.io>
description: |
  Keep the README.md `usage`, `inputs` and `outputs` in sync with the `action.yml` file.
  Additionally the Action's usage example is updated to match the Action's current release.

branding:
  icon: book-open
  color: yellow
inputs:
  action:
    description: >
      The absolute or relative path to the `action.yml` file to read in from.
    required: false
    default: action.yml
  readme:
    description: >
      The absolute or relative path to the markdown output file that contains
      the formatting tokens within it.
    required: false
    default: README.md
  owner:
    description: >
      The GitHub Action repository owner. i.e: `bitflight-devops`|`your-gh-username`
    required: false
  repo:
    description: >
      The GitHub Action repository name. i.e: `github-action-readme-generator`
    required: false
  save:
    description: >
      Save the provided values in a `.ghadocs.json` file. This will update
      any existing `.ghadocs.json` file that is in place.
    required: false
  pretty:
    description: >
      Use `prettier` to pretty print the new README.md file
    required: false
  versioning_enabled:
    description: >
      Enable the update of the usage version to match the latest version in the `package.json` file
    required: false
  version_override:
    description: >
      Set a specific version to display in the README.md
    required: false
  version_prefix:
    description: >
      Prefix the version with this value (if it isn't already prefixed)
    required: false
    default: v
  versioning_default_branch:
    description: >
      If versioning is disabled show this branch instead
    required: false
    default: main
  title_prefix:
    description: >
      Add a prefix to the README title
    required: false
    default: "GitHub Action: "
  include_github_version_badge:
    description: >
      Include additional badge showing latest tag
    required: false
    default: true
runs:
  using: "node20"
  main: "./dist/index.js"
