name: Licensed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  NODE_OPTIONS: "--no-network-family-autoselection"
  SKIP_PREFLIGHT_CHECK: true
jobs:
  call-licensed:
    name: Licensed
    uses: actions/reusable-workflows/.github/workflows/licensed.yml@main
