name: publish-action

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Update README.md
        uses: bitflight-devops/github-action-readme-generator@v1
      - run: git config --global init.defaultBranch main
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - name: Release GitHub Actions
        uses: technote-space/release-github-actions@v7.2.4
        with:
          COMMIT_NAME: ${{ github.event.head_commit.author.name }}
          COMMIT_EMAIL: ${{ github.event.head_commit.author.email }}
          PACKAGE_MANAGER: yarn
          BUILD_COMMAND: yarn build
          COMMIT_MESSAGE: "chore(release): ${{github.tag_name}}"
          BRANCH_NAME: main
          CREATE_MAJOR_VERSION_TAG: true
          BUILD_COMMAND_TARGET: build
          DELETE_NODE_MODULES: true
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
