name: publish-action

on:
  push:
    tags:
      - '**'

jobs:
  release:
    name: Release GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README.md
        uses: bitflight-devops/github-action-readme-generator@v1

      - name: Release GitHub Actions
        uses: technote-space/release-github-actions@v7.2.4
        with:
          PACKAGE_MANAGER: yarn
          BUILD_COMMAND: yarn build
          COMMIT_MESSAGE: 'chore(release): ${{github.tag_name}}'
          BRANCH_NAME: main
          CREATE_MAJOR_VERSION_TAG: true
